name: "EK Bibop"
description: "Action for executing Bibop test recipes"
author: "ESSENTIALKAOS"

branding:
  icon: 'bold'
  color: 'white'

inputs:
  recipe:
    description: "Path to Bibop recipe"
    required: true

  version:
    description: "Version of Bibop"
    required: false
    default: "8.1.2"

  dry-run:
    description: "Just parse and validate recipe"
    required: false

  format:
    description: "Output format (tap13|tap14|json|xml)"
    required: false

  working-dir:
    description: "Path to working directory"
    required: false

  path:
    description: "Path to directory with binaries"
    required: false

  tag:
    description: "Command tag"
    required: false

runs:
  using: "composite"
  steps:
    - id: bibop-bin-cache
      name: Cache bibop binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/bibop
        key: ${{runner.os}}-ek-bibop-action-v${{inputs.version}}

    - id: bibop-install
      name: Install Bibop
      if: steps.bibop-bin-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # [bibop-install]

        echo -e "::group::\033[34mDownloading Bibop…\033[0m"

        mkdir -p ~/.cache
        wget -O ~/.cache/bibop "https://apps.kaos.st/bibop/${{inputs.version}}/linux/x86_64/bibop" 2>&1
        chmod +x ~/.cache/bibop

        echo "::endgroup::"

    - id: bibop-set-options
      name: Set Bibop options
      shell: bash
      run : |
        # [bibop-set-options]

        declare -a options

        if [[ -n "${{inputs.dry-run}}" ]] ; then
          options+=("-D")
        fi

        if [[ -n "${{inputs.format}}" ]] ; then
          options+=("-f ${{inputs.format}}")
        fi

        if [[ -n "${{inputs.working-dir}}" ]] ; then
          options+=("-d ${{inputs.working-dir}}")
        fi

        if [[ -n "${{inputs.path}}" ]] ; then
          options+=("-p ${{inputs.path}}")
        fi

        if [[ -t "${{inputs.tag}}" ]] ; then
          options+=("-p ${{inputs.tag}}")
        fi

        echo -e "::group::\033[34mBibop configuration…\033[0m"
        if [[ ${#options[@]} -eq 0 ]] ; then
          echo "Options: -no-set-"
        else
          echo "Options: ${options[@]}"
        fi
        echo "::endgroup::"

        echo "options=${options[@]}" >> $GITHUB_OUTPUT

    - id: bibop-version-print
      name: Print Bibop version info
      shell: bash
      run: |
        # [bibop-version-print]

        echo -e "::group::\033[34mPrint Bibop version…\033[0m"
        ~/.cache/bibop --version
        echo "::endgroup::"

    - id: bibop-check
      name: Run Bibop recipes
      shell: bash
      run: |
        # [bibop-check]

        echo -e "\033[34mRunning Bibop…\033[0m"
        ~/.cache/bibop -ip ${{steps.bibop-set-options.outputs.options}} ${{inputs.recipe}}
